### ISSUE TITLE
重复引入 weixin-js-sdk 时，返回结果为空

### ISSUE THREAD

**Issue by yejiajiehz** [yanxi-me/weixin-js-sdk#10]
由于代码里会判断 window.jWeixin  
如果其他包里引用了 其他版本的 weixin-js-sdk ，再次引用时 window.jWeixin  已经存在
导致代码逻辑不正确

```
myproject
--node_modules
---- weixin-js-sdk@1.2.0     // 我自己安装的 sdk
---- ohter
--------eixin-js-sdk@1.0.7   // 第三方包引入的 sdk
```

应该添加一行代码
```
if(!window.jWeixin) {...} 
return window.jWeixin
```

我目前的处理方法是
```
const wx = window.jWeixin || require('weixin-js-sdk')
```

**Comment by aegisho** [comment]
如果是直接引入浏览器是不存在这个问题的
只有在 npm  多模块引用的情形下 会形成我上面的结构
CommonJS 版本需要处理这个问题

**Comment by yanxi-me** [comment]
> 由于代码里会判断 window.jWeixin
如果其他包里引用了 其他版本的 weixin-js-sdk ，再次引用时 window.jWeixin 已经存在
导致代码逻辑不正确

既然代码里判断了 window.jWeixin，如果之前引入过其他版本的包，再次引入时就不会执行相关代码啊

**Comment by yejiajiehz** [comment]
@yanxi-me 
```
const wx = require('weixin-js-sdk')
// 如果已经引用过，返回结果是 undefined
// 正确写法
const wx = window.jWeixin || require('weixin-js-sdk')
```

**Comment by yanxi-me** [comment]
新版本已经解决此问题
