### ISSUE TITLE
调用微信扫一扫功能的时候还没扫描二维码，就自动执行了扫描的回调了

### ISSUE THREAD

**Issue by huangche007** [yanxi-me/weixin-js-sdk#12]
` sendArticle(){
            this.isShowQRCode = true;

          wx.ready(function () {
            wx.checkJsApi({
              jsApiList : ['scanQRCode'],
              success : function(res) {
              }
            });
            wx.scanQRCode({
              needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
              scanType: ["qrCode"], // 可以指定扫二维码还是一维码，默认二者都有
              success: function (res) {
                var result = res.resultStr; // 当needResult 为 1 时，扫码返回的结果
                console.log("result:aaaaaaa",result);
                //                    window.location.href = result;//因为我这边是扫描后有个链接，然后跳转到该页面
              }
            });
          });

        },`

这个方法是点击一个按钮，然后扫描二维码，可是还没有扫描二维码，wx.scanQRCode的success就自动执行了

**Comment by yanxi-me** [comment]
请问问题解决了吗？ result 结果是什么

**Comment by yanxi-me** [comment]
微信 SDK 使用问题可以到官方社群询问 https://developers.weixin.qq.com/community/develop/
