### ISSUE TITLE
ssr中使用会报错，window is not defined

### ISSUE THREAD

**Issue by liumin1128** [yanxi-me/weixin-js-sdk#16]
如题

**Comment by ismjt** [comment]
@liumin1128 我也有一样的问题，不过我先这样处理了
`if (process.env.BROWSER) {
      import('weixin-js-sdk').then((wx) => {
        console.info(wx);
      });
    }`

**Comment by jamninetyfive** [comment]
@ismjt  这样做能在ssr中正常使用是么？

**Comment by aalenliang** [comment]
如果你用的是 Nuxt，可以用 ssr 为 false 的 plugin 来解决。

**/plugins/weixin-js-sdk.js**
```
import wx from 'weixin-js-sdk'

export default (ctx, inject) => {
  ctx.$wx = wx
  inject('wx', wx)
}
```

**nuxt.config.js**
```
module.exports = {
  plugins: [
    { src: '@/plugins/wx-js-sdk.js', ssr: false }
  ]
}
```

**/pages/index.vue**
```
<script>
export default {
  mounted: function() {
    fetchSignature().then(response => this.$wx.config({ ... }))
  }
}
</script>
```

**Comment by chen86860** [comment]
可以动态导入，在需要调用的地方导入，对于React来说：
```js
....
 componentDidMount(){
  import('weixin-js-sdk').then((wx) => {
    wx.ready(()=>{
      ...
    })
   })
}
...
```

**Comment by akeyboardlife** [comment]
> weixin-js-sdk
 
    Error while mounting app: Error: inject(key, value) has no value provided

为什么我出现这个错误。

**Comment by yanxi-me** [comment]
最新版本已解决此问题，在服务端执行时不会报错了

**Comment by laoona** [comment]
> 最新版本已解决此问题，在服务端执行时不会报错了

好用，可以不打印 warn 信息吗？
` if (!r) {
    console.warn("can't use weixin-js-sdk in server side");
    return;
  }`

**Comment by yanxi123-com** [comment]
> > 最新版本已解决此问题，在服务端执行时不会报错了
> 
> 好用，可以不打印 warn 信息吗？ ` if (!r) { console.warn("can't use weixin-js-sdk in server side"); return; }`

这只是提醒，在服务端不会执行，也不会有实质影响。
