### ISSUE TITLE
调用chooseImage，提示 wx is not define

### ISSUE THREAD

**Issue by liupl** [yanxi-me/weixin-js-sdk#18]
查看源码发现选择图片后会调用wx.ready方法，但wx没有定义，会报错，实际应该N.ready方法

**Comment by zsio** [comment]
请问您解决这个问题了吗？   我遇到了   太坑了    项目写到现在了   根本没法换了

**Comment by liupl** [comment]
解决了，要改源码，你提了PR，你可以去看一下

**Comment by liupl** [comment]
解决了，要改源码，我提了PR，你可以去看一下

**Comment by zsio** [comment]
哎呀 太感谢了    终于解决了  明天下午要上线   这个bug折腾我两天了   睡觉的睡不好

**Comment by yanxi-me** [comment]
多谢 @liupl 代码已经合并
