### ISSUE TITLE
使用wx.chooseImage()选择相册中的图片后，如何在页面以缩略图的形式回显这些图片呢？

### ISSUE THREAD

**Issue by preservance717** [yanxi-me/weixin-js-sdk#21]
使用wx.chooseImage()选择相册中的图片后，如何在页面以缩略图的形式回显这些图片呢？

**Comment by LiJohnson** [comment]
这个 wx.previewImage
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/JS-SDK.html#18

**Comment by yanxi-me** [comment]
微信的官方 sdk 貌似不支持缩略图
