### ISSUE TITLE
wx.config is not defound

### ISSUE THREAD

**Issue by Jwiayou** [yanxi-me/weixin-js-sdk#23]
![image](https://user-images.githubusercontent.com/22660464/42720326-c380480a-8757-11e8-8b75-1b9b3180eb64.png)

**Comment by Jwiayou** [comment]
wx 对象输出为空

**Comment by yanxi-me** [comment]
已经修复此问题，请升级至 weixin-js-sdk@1.3.3

**Comment by kunkuntang** [comment]
![image](https://user-images.githubusercontent.com/13299413/43122215-d5628a3a-8f52-11e8-96ef-30c136a78ac7.png)
![image](https://user-images.githubusercontent.com/13299413/43122304-2953468e-8f53-11e8-87af-a35f9394532d.png)

when I update to 1.3.3 version, the problem still appeared.

**Comment by yanxi-me** [comment]
可能是你的依赖也引入过这个库导致的。

试试:
`const wx = window.jWeixin || require('weixin-js-sdk')`

**Comment by yanxi-me** [comment]
最新的版本已解决重复引入包的问题
