### ISSUE TITLE
getLocalImgData接口报错

### ISSUE THREAD

**Issue by zsio** [yanxi-me/weixin-js-sdk#24]
提示wx找不到

请问如何解决  很着急

**Comment by yanxi-me** [comment]
已经更新代码，请升级到 weixin-js-sdk@1.3.3

**Comment by kyoa** [comment]
> 已经更新代码，请升级到 weixin-js-sdk@1.3.3

在1.6.0版本里仍然出现这个bug，请问如何解决

**Comment by eadio** [comment]
你的邮件我已收到，我会尽快处理。。。。

**Comment by yanxi-me** [comment]
估计是由于重复引入包导致，最新版本已解决此问题。

**Comment by zsio** [comment]
5 年过去了
