### ISSUE TITLE
请求升级

### ISSUE THREAD

**Issue by crossgit** [yanxi-me/weixin-js-sdk#25]
现在官方出的1.4.0了...

"请注意，原有的 wx.onMenuShareTimeline、wx.onMenuShareAppMessage、wx.onMenuShareQQ、wx.onMenuShareQZone 接口，即将废弃。请尽快迁移使用客户端6.7.2及JSSDK 1.4.0以上版本支持的 wx.updateAppMessageShareData、updateTimelineShareData 接口。"

**Comment by limi58** [comment]
+1

**Comment by AlwaysSkylll** [comment]
1.4.0 sdk 会向下兼容吗？ 兼容老得微信版本的分享吗？

**Comment by AlwaysSkylll** [comment]
看了下我自己的微信才6.7.1

**Comment by chenchaoc** [comment]
+1

**Comment by mikeros147** [comment]
+1

**Comment by syhyz1990** [comment]
求升级

**Comment by yanxi-me** [comment]
最近没有做微信下开发，所以更新比较迟，如果有人可以完成 1.4.0 版改动，请提交 merge request，将会非常感激！

**Comment by HadiChen** [comment]
已提交pr https://github.com/yanxi-me/weixin-js-sdk/pull/27
