### ISSUE TITLE
ios下SPA history跳转后，长按图片无法「发送给朋友」和「识别二维码」

### ISSUE THREAD

**Issue by llyo** [yanxi-me/weixin-js-sdk#26]
使用vue做的SPA，router.mode='history'
本来ios下分享时会出现签名的问题，通过一直使用“首次进入的url”来获取签名可以解决签名的问题，
但是长按图片还是无法弹出「发送给朋友」和「识别二维码」
不知道是什么问题
望解答，谢谢~

**Comment by Musiker1114** [comment]
> 使用vue做的SPA，router.mode='history'
> 本来ios下分享时会出现签名的问题，通过一直使用“首次进入的url”来获取签名可以解决签名的问题，
> 但是长按图片还是无法弹出「发送给朋友」和「识别二维码」
> 不知道是什么问题
> 望解答，谢谢~

我也遇到相同的问题，经过多番检查，发现进入页面的时候，带的参数是url链接，url链接必须encodeURIComponent后再作为参数，页面生成的二维码在ios中才能正确的识别

**Comment by levinzero** [comment]
@Musiker1114 如果我是微信授权页跳转进来呢？链接本身已经是encode过的了

**Comment by yanxi-me** [comment]
微信 sdk 使用问题，请参考官方文档或者官方交流区 https://developers.weixin.qq.com/community/develop/
