### ISSUE TITLE
wx.agentConfig调用不了，方法undefined

### ISSUE THREAD

**Issue by zy188260** [yanxi-me/weixin-js-sdk#29]
依赖包1.3.3或者1.4.0.test都调用不了这个方法，企业微信api

**Comment by kevinchung1026** [comment]
我是 wx.agentConfig 在安卓机上调用不了，在苹果机上没问题

**Comment by kevinchung1026** [comment]
> 依赖包1.3.3或者1.4.0.test都调用不了这个方法，企业微信api

目前的解决办法是在线引入微信官方的cdn，用全局变量去获取 js-sdk

**Comment by shangTou** [comment]
我的解决办法是config的时候jsApiList包含agentConfig，使用wx.invoke('agentConfig')进行调用即可，代码如下

`
wx.config({
        beta: true, // 这个官方文档说要为true
        debug: true,
        appId: '',
        timestamp: '',
        nonceStr: '',
        signature: '',
        jsApiList: ['agentConfig', ....]
});

wx.ready(function(res: any) {
    wx.checkJsApi({
        jsApiList: [],
        success: function (res: any) {
          return;
        },
    });

    wx.invoke(
        'agentConfig',
        {
          agentid:  '',  // 这个格式为字符串
          corpid: '',
          timestamp:'',
          nonceStr: '',
          signature: '',
          jsApiList: [],
        },
        function (res: any) {
          return;
        },
     );
})

`

**Comment by shangTou** [comment]
我的解决办法是config的时候jsApiList包含agentConfig，使用wx.invoke('agentConfig')进行调用即可，代码如下

`
wx.config({
        beta: true, // 这个官方文档说要为true
        debug: true,
        appId: '',
        timestamp: '',
        nonceStr: '',
        signature: '',
        jsApiList: ['agentConfig', ....]
});

wx.ready(function(res: any) {
    wx.checkJsApi({
        jsApiList: [],
        success: function (res: any) {
          return;
        },
    });

    wx.invoke(
        'agentConfig',
        {
          agentid:  '',  // 这个格式为字符串
          corpid: '',
          timestamp:'',
          nonceStr: '',
          signature: '',
          jsApiList: [],
        },
        function (res: any) {
          return;
        },
     );
})
`

**Comment by shangTou** [comment]
我的解决办法是config的时候jsApiList包含agentConfig，使用wx.invoke('agentConfig')进行调用即可，代码如下

`


    wx.config({
        beta: true, // 这个官方文档说要为true
        debug: true,
        appId: '',
        timestamp: '',
        nonceStr: '',
        signature: '',
        jsApiList: ['agentConfig', ....]
    });

    wx.ready(function(res: any) {
        wx.checkJsApi({
            jsApiList: [],
           success: function (res: any) {
              return;
           },
        });

        wx.invoke(
            'agentConfig',
            {
              agentid:  '',  // 这个格式为字符串
              corpid: '',
              timestamp:'',
              nonceStr: '',
              signature: '',
              jsApiList: [],
            },
            function (res: any) {
              return;
            },
         );
    })

`

**Comment by julietdesigner** [comment]
` if(!wx.agentConfig){
                            console.log('=======reload', wx);
                            window.location.reload();
                        }`

**Comment by yanxi-me** [comment]
可以升级到最新版本再试试
