### ISSUE TITLE
1.2.0版是否支持https

### ISSUE THREAD

**Issue by wayne163** [yanxi-me/weixin-js-sdk#3]
[微信JS-SDK说明文档](https://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E6.AD.A5.E9.AA.A4.E4.BA.8C.EF.BC.9A.E5.BC.95.E5.85.A5JS.E6.96.87.E4.BB.B6) 中还在使用1.0.0（支持https） 

1.2.0是否也支持https？

**Comment by yanxi-me** [comment]
支持的
