### ISSUE TITLE
用babel转换之后，export导出为空，

### ISSUE THREAD

**Issue by lou920217** [yanxi-me/weixin-js-sdk#35]
![image](https://user-images.githubusercontent.com/5370271/53472739-78117100-3aa3-11e9-809a-faf7f93ae470.png)
```
var wx = require('weixin-js-sdk');
console.log(wx);   // {__esModule: true}
```
使用babel-loader转换后，export导出的对象是空的；

![image](https://user-images.githubusercontent.com/5370271/53472962-18679580-3aa4-11e9-8e6f-eb2d7efe1872.png)

而且用es6的import引入包时，会报warning，

![image](https://user-images.githubusercontent.com/5370271/53473117-82803a80-3aa4-11e9-8af3-39a99f5721b8.png)

这个是什么问题呢？

**Comment by yanxi-me** [comment]
请问问题解决了吗？

**Comment by yanxi-me** [comment]
帖子时间比较久了，我先关闭，如果未解决可以重新打开。
