### ISSUE TITLE
api-微信支付支持缺陷

### ISSUE THREAD

**Issue by snailycy** [yanxi-me/weixin-js-sdk#36]
api-微信支付，填坑：传参得传timestamp(s小写，微信文档上是timeStamp)，appId缺失，导致出现"支付验证签名失败"

**Comment by Imday** [comment]
> api-微信支付，填坑：传参得传timestamp(s小写，微信文档上是timeStamp)，appId缺失，导致出现"支付验证签名失败"

正解。

**Comment by yanxi-me** [comment]
sdk 使用遇到的问题，可以参考 https://developers.weixin.qq.com/community/pay/doc/0008c6b37741107b8568a7f1659400
