### ISSUE TITLE
chooseImage唤起相册很慢

### ISSUE THREAD

**Issue by Anthony0416** [yanxi-me/weixin-js-sdk#39]
使用1.4sdk 调用chooseImage时在小米mix3，荣耀9等机型上从触发事件到显示相册需要等待5秒以上，换回1.2版本就基本秒开了。

**Comment by yanxi-me** [comment]
SDK 使用问题可以来微信社区询问 https://developers.weixin.qq.com/community/pay/doc/0008c6b37741107b8568a7f1659400
