### ISSUE TITLE
nodes v7.10.0下问题

### ISSUE THREAD

**Issue by yolo2013** [yanxi-me/weixin-js-sdk#4]
node_modules/weixin-js-sdk/index.js (1:108) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
(node:12540) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 'default' is not exported by node_modules/weixin-js-sdk/index.js
(node:12540) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by yanxi-me** [comment]
已解决此问题，不会报错，但 weixin-js-sdk 只支持浏览器，在 nodejs 中无法运行
