### ISSUE TITLE
用的是1.40-test,IOS端getLocalImgData失败

### ISSUE THREAD

**Issue by Niubility-SunLight** [yanxi-me/weixin-js-sdk#40]
用的是1.40-test,IOS端getLocalImgData失败，返回getLocalImgData:fail。已经通过chooseImage拿到本地localId，当调用getLocalImgData转为Base64时候，没走成功回调，走的失败回调

**Comment by Niubility-SunLight** [comment]
查看了下源码，问题暂时已解决、源码调用getLocalImgData的时候用的是wx.ready和wx.getLocalImgData。但是源码中并没有引入wx。最后在html中，加入<script src="http://res.wx.qq.com/open/js/jweixin-1.4.0.js"></script>暂时解决问题

**Comment by yanxi-me** [comment]
最新版本此问题已解决，请升级到最新版本
