### ISSUE TITLE
agentConfig is not a function

### ISSUE THREAD

**Issue by TanChenkun** [yanxi-me/weixin-js-sdk#42]
agentConfig is not a function，微信开发者工具，注入agentConfig时候报错

**Comment by shangTou** [comment]
我的解决办法是config的时候jsApiList包含agentConfig，使用wx.invoke('agentConfig')进行调用即可，代码如下

`

wx.config({
    beta: true, // 这个官方文档说要为true
    debug: true,
    appId: '',
    timestamp: '',
    nonceStr: '',
    signature: '',
    jsApiList: ['agentConfig', ....]
});

wx.ready(function(res: any) {
    wx.checkJsApi({
        jsApiList: [],
       success: function (res: any) {
          return;
       },
    });

    wx.invoke(
        'agentConfig',
        {
          agentid:  '',  // 这个格式为字符串
          corpid: '',
          timestamp:'',
          nonceStr: '',
          signature: '',
          jsApiList: [],
        },
        function (res: any) {
          return;
        },
     );
})

`

**Comment by shangTou** [comment]
我的解决办法是config的时候jsApiList包含agentConfig，使用wx.invoke('agentConfig')进行调用即可，代码如下

`

  wx.config({
      beta: true, // 这个官方文档说要为true
      debug: true,
      appId: '',
      timestamp: '',
      nonceStr: '',
      signature: '',
      jsApiList: ['agentConfig', ....]
  });

wx.ready(function(res: any) {
    wx.checkJsApi({
        jsApiList: [],
       success: function (res: any) {
          return;
       },
    });

    wx.invoke(
        'agentConfig',
        {
          agentid:  '',  // 这个格式为字符串
          corpid: '',
          timestamp:'',
          nonceStr: '',
          signature: '',
          jsApiList: [],
        },
        function (res: any) {
          return;
        },
     );
})

`

**Comment by shangTou** [comment]
`

    wx.config({
        beta: true, // 这个官方文档说要为true
        debug: true,
        appId: '',
        timestamp: '',
        nonceStr: '',
        signature: '',
        jsApiList: ['agentConfig', ....]
    });

    wx.ready(function(res: any) {
        wx.checkJsApi({
            jsApiList: [],
           success: function (res: any) {
              return;
           },
        });

    wx.invoke(
        'agentConfig',
        {
          agentid:  '',  // 这个格式为字符串
          corpid: '',
          timestamp:'',
          nonceStr: '',
          signature: '',
          jsApiList: [],
        },
        function (res: any) {
          return;
        },
     );
})

`

**Comment by shangTou** [comment]
我的解决办法是config的时候jsApiList包含agentConfig，使用wx.invoke('agentConfig')进行调用即可，代码如下

`

    wx.config({
        beta: true, // 这个官方文档说要为true
        debug: true,
        appId: '',
        timestamp: '',
        nonceStr: '',
        signature: '',
        jsApiList: ['agentConfig', ....]
    });

    wx.ready(function(res: any) {
        wx.checkJsApi({
            jsApiList: [],
           success: function (res: any) {
              return;
           },
        });

      wx.invoke(
          'agentConfig',
          {
            agentid:  '',  // 这个格式为字符串
            corpid: '',
            timestamp:'',
            nonceStr: '',
            signature: '',
            jsApiList: [],
          },
          function (res: any) {
            return;
          },
       );
    })`
