### ISSUE TITLE
请问下还更新嘛jweixin-1.6.0.js

### ISSUE THREAD

**Issue by 2277419213** [yanxi-me/weixin-js-sdk#43]
微信jsdk已经升级到了1.6.0版本，看了git主的好像好像还停留在1.4.0版本的阶段，想问问git主还更新嘛

**Comment by vanbolee** [comment]
我fork了一份更新到了1.6.0，你可以一样使用

**Comment by vanbolee** [comment]
> 微信jsdk已经升级到了1.6.0版本，看了git主的好像好像还停留在1.4.0版本的阶段，想问问git主还更新嘛

我fork了一份更新到了1.6.0，你可以一样使用

**Comment by OriginalCobra** [comment]
> > 微信jsdk已经升级到了1.6.0版本，看了git主的好像好像还停留在1.4.0版本的阶段，想问问git主还更新嘛
> 
> 我fork了一份更新到了1.6.0，你可以一样使用

请问怎么使用啊？

**Comment by yanxi-me** [comment]
> > 微信jsdk已经升级到了1.6.0版本，看了git主的好像好像还停留在1.4.0版本的阶段，想问问git主还更新嘛
> 
> 我fork了一份更新到了1.6.0，你可以一样使用

多谢~ 已经合并你的改动到本仓库，新版本也更新到了 npm

**Comment by yanxi-me** [comment]
> > > 微信jsdk已经升级到了1.6.0版本，看了git主的好像好像还停留在1.4.0版本的阶段，想问问git主还更新嘛
> > 
> > 
> > 我fork了一份更新到了1.6.0，你可以一样使用
> 
> 请问怎么使用啊？

1.6.0 版本已经更新，现在直接安装就可以使用了

**Comment by OriginalCobra** [comment]
真给力，我昨晚才从vanbolee这安装的

> > > > 微信jsdk已经升级到了1.6.0版本，看了git主的好像好像还停留在1.4.0版本的阶段，想问问git主还更新嘛
> > > 
> > > 
> > > 我fork了一份更新到了1.6.0，你可以一样使用
> > 
> > 
> > 请问怎么使用啊？
> 
> 1.6.0 版本已经更新，现在直接安装就可以使用了

真给力，我昨晚才从vanbolee这安装的

**Comment by OriginalCobra** [comment]
顺便想请教一个问题，像我下面这样，为什么在小程序页面不能接受参数呢？events和success都没有执行感觉。

`wx.miniProgram.navigateTo({
        url: `/pages/pay/index?param=${payParamQueryString}`,
        events: {
          // 监听支付成功或取消事件，刷新数据
          onPayment: function(data) {
            resolve(data)
          }
        },
        success: function(res) {
          // 通过eventChannel向被打开页面传送数据
          res.eventChannel.emit('acceptDataFromOpenerPage', { data: 'test' })
        }
      })`

**Comment by yanxi-me** [comment]
> 顺便想请教一个问题，像我下面这样，为什么在小程序页面不能接受参数呢？events和success都没有执行感觉。

最近没做这方面的开发，就帮不上忙了

**Comment by OriginalCobra** [comment]
好的好的

**Comment by yanxi-me** [comment]
> 微信jsdk已经升级到了1.6.0版本，看了git主的好像好像还停留在1.4.0版本的阶段，想问问git主还更新嘛

已更新 1.6.0
