### ISSUE TITLE
ios和部分安卓，微信长按识别二维码总是调起系统的保存图片功能，没有二维码选项

### ISSUE THREAD

**Issue by monologueH** [yanxi-me/weixin-js-sdk#46]
#### 长按img标签识别图中的二维码的时候，总是会拉起ios的3D-touch功能，部分安卓也是会触发系统的菜单，无法识别，请问这个怎么解决?
![Image of Yaktocat](https://robot-vr-public.cdn.bcebos.com/image/2ad27080-66b5-af89-41ea-9deb2610191f.jpeg)

**Comment by yanxi-me** [comment]
使用问题可以到官方社区询问 https://developers.weixin.qq.com/community/pay/doc/0008c6b37741107b8568a7f1659400
