### ISSUE TITLE
收货地址共享问题

### ISSUE THREAD

**Issue by menzil** [yanxi-me/weixin-js-sdk#5]
[开发文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_8&index=7&pass_ticket=%2F7FuG7Sfwg8SD6yXMmDL8n2zXRSBOD%2FX0KIMg8XL0RrG%2B9PiQyBhZ04iqeoAxa0C)
特别注意：JS-SDK版本需使用http://res.wx.qq.com/open/js/jweixin-1.1.0.js
怎么办？

**Comment by yanxi-me** [comment]
已经升级到 1.6.0
