### ISSUE TITLE
安卓使用onPageStateChange，监听页面变化，不生效，ios可以

### ISSUE THREAD

**Issue by snail-boy** [yanxi-me/weixin-js-sdk#51]
WeixinJSBridge.on('onPageStateChange', function(res) {
        // 注意：res.active返回的是字符串类型的true和false
         if (res && res.active) {
          // do something
          console.log('onready')
        }
      })

  <wx-open-launch-weapp
                    class="now-btn"
                    id="launch-btn"
                    username="gh_a974b946349a"
                    :path="weChatPath"
                    @ready='onReady'
                    @launch="onLaunch"
                    @error="onError"
                  >
                    <script type="text/wxtag-template">
                        <style>.btn { color: #fff; font-size: 17px; height: 55px; line-height: 55px; text-align: center }</style>
                        <div class='btn other-btn'>下一步</div>
                    </script>
         </wx-open-launch-weapp>

公众号上打开小程序后，退出小程序回到公众号，调用页面变化的微信sdk方法，ios可以成功，安卓不行为什么？着急

**Comment by yanxi-me** [comment]
使用问题可以到微信官方社群寻求帮助 https://developers.weixin.qq.com/community/pay/doc/0008c6b37741107b8568a7f1659400
