### ISSUE TITLE
安装成功后引用wx,打印的值为undefined

### ISSUE THREAD

**Issue by sunpeng-hub** [yanxi-me/weixin-js-sdk#52]
根据官方提供安装npm install weixin-js-sdk，之后引用import wx from "weixin-js-sdk",提示无法找到模块“weixin-js-sdk”的声明文件。“C:/Users/lenovo/Desktop/qiaohan-billboard/minip-wx/node_modules/weixin-js-sdk/index.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/weixin-js-sdk` (如果存在)，或者添加一个包含 `declare module 'weixin-js-sdk';` 的新声明(.d.ts)文件，但是在此之前，确实是好使的，并没有做任何的更改

**Comment by eadio** [comment]
你的邮件我已收到，我会尽快处理。。。。

**Comment by allenliu123** [comment]
我也遇到相同的问题

**Comment by sunpeng-hub** [comment]
> 我也遇到了相同的问题
我的wx之所以打印出来是undefined是因为我在安装完依赖之后又在index.html中引入了https ://res.wx.qq.com/open/js/jweixin-1.6.0.js，至于它提示的的那个地方没有影响的

**Comment by allenliu123** [comment]
> > 我也遇到了相同的问题
> > 我的wx之所以打印出来是undefined是因为我在安装完依赖之后又在index.html中引入了https ://res.wx.qq.com/open/js/jweixin-1.6.0.js，至于它提示的的那个地方没有影响的

我并没有在 index.html 引入任何的 weixin js，也会报 undefined，现在的解决方式是在 main.js 里面引入 weixin-js-sdk, 并绑定到window 上，后面使用的时候在 window 上去取，这样是可以使用的。

**Comment by yanxi-me** [comment]
已解决此问题，请升级到 weixin-js-sdk@1.6.1 版本
