### ISSUE TITLE
launch_3rdApp:fail_invalid signature

### ISSUE THREAD

**Issue by sharp00k** [yanxi-me/weixin-js-sdk#7]
WeixinJSBridge.invoke('launch3rdApp', {
'appid': 'xxxxxxx',
'messageExt': 'from=weixin_webview',
'extInfo': 'from=weixin_webview'
}, function(e) {
alert("error" + JSON.stringify(e));
});

launch_3rdApp:fail_invalid signature

help me

**Comment by eadio** [comment]
你的邮件我已收到，我会尽快处理。。。。
